---
title: "Geospatial Analytics Project"
subtitle: Democratising Geospatial Data and Analytics with Shiny App
format: html
---

## Overview

The purpose of the geospatial analytics project is to provide students first hand experience on building web-based geospatial analytics tool by integrating open source web mapping API(s), data visualisation API(s) and geospatial analysis libraries. You will also learn how to collecting, processing and analysing spatially related issues using real world data. Students are encouraged to focus on research topics that are relevant to their field of study.

The project is team work. Students are required to form a project team of **2-3** members by the first week of the academic term. Each project teams must start thinking about their project ideas after the first lesson. They are expected to discuss their project topic and scope of works with the instructor before the end of **Week 8**. A project proposal in the form website edited using [Quarto](https://quarto.org/docs/websites/) and publish on [Netlify](https://www.netlify.com/) will be prepared and the link must be provided on eLearn by the end of **Week 8**.

The project proposal should describe the motivation of the project, problems or issues that the project will address, the relevant related work, the approach the team plans to take to solve the problem, and early prototypes or storyboards. The project teams should take advantage of this proposal as a chance to get feedback on the direction of the project from their peers.

Students are required to update their project websites with all the details including the final application, user guide, poster, practice research paper by **the end of week 14**.

## Project Theme

Students are required to choose one of the following theme to develop the GeoSpaital Analytics Project:

-   Spatial Point Patterns Analysis
-   Exploratory Spatial Data Analysis
-   Analytical Regionalisation and Geographical Segmentation
-   Geographically Weighted Regression Models
-   Flow and Movement Data Analytics
-   Geographical Accessibility and Spatial Interaction Models

Please feel free to approach me for more details.

## Project Milestone

-   Brainstorming project ideas and consulting with course instructor between **Week 2 to Week 7**.
-   Editing and publishing project proposal by the end of **Week 8**.
-   Submission of final application, user guide, project poster, practice research paper and artifacts: **16th April 2023 by 11:59pm (mid-night)**

## Project Deliverables

### Project Website

#### Project Github

At the beginning of the project, project teams are required to create a project [Github](https://github.com/). The project Github should include all the materials used to develop the project and the written materials such as proposal, poster and practice research paper. It must be used to maintain a complete project versioning including the application and project documents. The Github link must be included in the project proposal. By the end of the project, the project team must pack the final version of the Github repository and upload onto eLearn for final submission. The Github link also must be provided on eLearn.

#### Project Website

Each project team are required to create the project website by using [Quatro](https://quarto.org/docs/websites/). It will be disseminated by using [Netfity](https://www.netlify.com/) web service.

As a first step, you should create a project summary at the course wiki that includes:

-   The title of your project,
-   A short description of not more than 350 word summarising the motivation, objectives, main features of the application your team are going to build, and
-   The project proposal. This should in a webblog page (remember to provide a link at eLearn).

### Poster

The project poster should provide an overview of your project. It should include, but not limited to the following information:

-   Issues and problems - A clear statement of the issues or/and problems your project addresses.

-   Motivation - An explanation of why the issues and/or problems are interesting and what make them difficult to solve.

-   Approach - A description of the techniques or algorithms you used to solve the problem.

-   Results - Screenshots and a working demo of the system you built.

-   Future Work - An explanation of how the work could be extended.

**Note:** The poster will be considered a final deliverable, so don't forget to apply good visual design and data visualisation principles and best practice to your poster.

### Geospatial Analytics Application Practice Research Paper

The research paper should be in the form of Geospatial Analytics Application practice and research. In particular it should contain the followings:

-   Motivation of the application
-   Review and critic on past works
-   Design framework - A detail description of the design principles used and data visualisation elements built (Refer to Section IV: Interface of this [paper](https://ink.library.smu.edu.sg/cgi/viewcontent.cgi?article=2760&context=sis_research).
-   Demonstration - Use case
-   Discussion - What has the audience learned from your work? What new insights or practices has your system enabled? A full blown user study is not expected, but informal observations of use that help evaluate your system are encouraged.
-   Future Work - A description of how your system could be extended or refined.

The research paper should include an abstract of **not more than 300 words**. The actual research paper itself should **not more than 6 pages** excluding figures, tables, formula and references. The practice research paper must be edited by using **ACM: Association for Computing Machinery** template of [Quarto Journal/Article](https://quarto.org/docs/journals/formats.html) template should be used.

#### Sample practice research papers

-   [DIVAD: A Dynamic and Interactive Visual Analytical Dashboard for Exploring and Analyzing Transport Data](https://ink.library.smu.edu.sg/sis_research/1761/)
-   [MEPHAS: an interactive graphical user interface for medical and pharmaceutical statistical analysis with R and Shiny](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-3494-x)
-   [SpatialEpiApp: A Shiny Web Application for the Analysis of Spatial and Spatio-Temporal Disease Data](https://cran.rstudio.com/web/packages/SpatialEpiApp/vignettes/manual.pdf)
-   [Developing web-based data analysis tools for precision farming using R and Shiny](https://iopscience.iop.org/article/10.1088/1755-1315/20/1/012014)
-   [EHDViz: clinical dashboard development using open-source technologies](https://www.ncbi.nlm.nih.gov/pubmed/27013597)
-   [Health Equity Assessment Toolkit](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-016-0229-9)
-   [Interactive Pharmacometric Applications Using R and the Shiny Package](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4394611/)

### Final Deliverables

The final deliverable will include:

-   artifact including the ShinyApp, data and all r modules.
-   User Guide - Step-by-step guide on how to use the data visualisation functions designed.
-   project poster
-   a practice research paper

## Grading

The geospatial analytics project will account for 30% of your final grade in the course. The distribution of marks for each stage of the project are as follows:

-   Project website 20%
-   Poster 10%
-   Practice Research Paper 25%
-   ShinyApp 45%

The course instructor will consider strongly the novelty of the idea (If it has never been done before, you will get lots of credit!), how it addresses the problem at hand, the methodology you employ in doing the research, and your technical skill in implementing the idea.

In small group projects, each person will be graded individually. A good group project is a system consisting of a collection of well defined subsystems. Each subsystem should be the responsibility of one person and be clearly identified as their project. A good criteria for whether you should work in a group is whether the system as a whole is greater than the sum of its parts!

### Grading criteria for poster

The poster will be graded based on the following criteria:

-   Clear communication of key aspects of solution
-   Clear communication of design approaches
-   Clear communication of arguments for proposed solution
-   Craft quality of the solution

## Learning from past project

-   AY2018-19 Term 2
    -   [Signal](https://wiki.smu.edu.sg/1819t2is415/Signal_Proposal) and the [Shiny application](https://is415-ay1819-signal.shinyapps.io/Signal/).
-   AY2020-2021 Term 1
    -   [J-Town](https://is415-t14-project-proposal.netlify.app/) and the [Shiny Application](https://erika-aldisa-gunawan.shinyapps.io/IS415_T14_EastKalimantan_New_JTown/)
-   AY2021-2022 Term 1
    -   Group 1: [Spatial Interaction Model](https://flosg-is415.netlify.app/)
    -   Group 3: [Regionalisation in Reach](https://is412-g3-proposal.netlify.app/posts/welcome/)
    -   Group 5: [Geographically Weighted Regression](https://g5-is415-proj.netlify.app/)
    -   Group 7: [GeoeXplorer](https://geoxplorer.netlify.app/), a web-enabled geospatial analytics toolkit for detecting and visualising global spatial autocorrelation and local clusters and outliers from univariate geographically referenced data.
    -   Group 8: [Spatial Pointers](https://spatial-pointers.netlify.app/project-proposal), a web-enabled Spatial Point Patterns Analysis toolkit for visualising and analysing both spatial and network constrained point patterns.

## Project Links




