---
title: "Take-home Exercise 3: Predicting HDB Public Housing Resale Pricies using Geographically Weighted Methods"
date: "10 February 2023"
date-modified: "`r Sys.Date()`"
format: html
editor: visual
---

::: callout-note
This handout provides the context, the task, the expectation and the grading criteria of Take-home Exercise 3. Students must review and understand them before getting started with the take-home exercise.
:::

## Setting the Scene

Housing is an essential component of household wealth worldwide. Buying a housing has always been a major investment for most people. The price of housing is affected by many factors. Some of them are global in nature such as the general economy of a country or inflation rate. Others can be more specific to the properties themselves. These factors can be further divided to structural and locational factors. Structural factors are variables related to the property themselves such as the size, fitting, and tenure of the property. Locational factors are variables related to the neighbourhood of the properties such as proximity to childcare centre, public transport service and shopping centre.

Conventional, housing resale prices predictive models were built by using [**Ordinary Least Square (OLS)**](https://en.wikipedia.org/wiki/Ordinary_least_squares) method. However, this method failed to take into consideration that spatial autocorrelation and spatial heterogeneity exist in geographic data sets such as housing transactions. With the existence of spatial autocorrelation, the OLS estimation of predictive housing resale pricing models could lead to biased, inconsistent, or inefficient results (Anselin 1998). In view of this limitation, **Geographical Weighted Models** were introduced for calibrating predictive model for housing resale prices.

## The Task

In this take-home exercise, you are tasked to predict HDB resale prices at the sub-market level (i.e. HDB 3-room, HDB 4-room and HDB 5-room) for the month of January and February 2023 in Singapore. The predictive models must be built by using by using conventional OLS method and GWR methods. You are also required to compare the performance of the conventional OLS method versus the geographical weighted methods.

## The Data

For the purpose of this take-home exercise, [`HDB Resale Flat Prices`](https://data.gov.sg/dataset/resale-flat-prices) provided by Data.gov.sg should be used as the core data set. The study should focus on either three-room, four-room or five-room flat and transaction period should be from 1st January 2021 to 31st December 2022. The test data should be January and February 2023 resale prices.

Below is a list of recommended predictors to consider. However, students are free to include other appropriate independent variables.

-   Structural factors
    -   Area of the unit
    -   Floor level
    -   Remaining lease
    -   Age of the unit
    -   Main Upgrading Program (MUP) completed (optional)
-   Locational factors
    -   Proxomity to CBD
    -   Proximity to eldercare
    -   Proximity to foodcourt/hawker centres
    -   Proximity to MRT
    -   Proximity to park
    -   Proximity to good primary school
    -   Proximity to shopping mall
    -   Proximity to supermarket
    -   Numbers of kindergartens within 350m
    -   Numbers of childcare centres within 350m
    -   Numbers of bus stop within 350m
    -   Numbers of primary school within 1km

## Grading Criteria

This exercise will be graded by using the following criteria:

-   **Geospatial Data Wrangling (20 marks):** This is an important aspect of geospatial analytics. You will be assessed on your ability to employ appropriate R functions from various R packages specifically designed for modern data science such as readxl, tidyverse (tidyr, dplyr, ggplot2), sf just to mention a few of them, to perform the entire geospatial data wrangling processes, including. This is not limited to data import, data extraction, data cleaning and data transformation. Besides assessing your ability to use the R functions, this criterion also includes your ability to clean and derive appropriate variables to meet the analysis need. (Warning: All data are like vast grassland full of land mines. Your job is to clear those mines and not to step on them).

-   **Geospatial Analysis and Modelling (30 marks):** In this exercise, you are expected to use appropriate statistical analysis and GWR functions introduced in class to calibrate hedonic price models. The focus of this criterion should go beyond discussing the modelling results, but include Exploratory Data Analysis, multivariate analysis analysis for detecting multicollinearity, and spatial autocorrelation test, just to name a few of them.

-   **Geovisualisation (20 marks):** In this section, you will be assessed on your ability to communicate the complex spatial statistics results in business friendly visual representations. This course is geospatial centric, hence, it is important for you to demonstrate your competency in using appropriate geovisualisation techniques to reveal and communicate the findings of your analysis.

-   **Reproducibility (20 marks):** This is an important learning outcome of this exercise. You will be assessed on your ability to provide a comprehensive documentation of the analysis procedures in the form of code chunks of RMarkdown. It is important to note that it is not enough by merely providing the code chunk without any explanation on the purpose and R function(s) used.

-   **Bonus (10 marks):** Demonstrate your ability to employ methods beyond what you had learned in class to gain insights from the data. The methods used must be geospatial in nature.

## Submission Instructions

-   The write-up of the take-home exercise must be in **Quarto html document** format. You are required to publish the write-up on [**Netlify**](https://www.netlify.com/).
-   The R project of the take-home exercise must be pushed onto your [Github](https://github.com/) repository.
-   You are required to provide the links to Netlify service of the take-home exercise write-up and github repository on eLearn.

## Due Date

~~19th March 2023 (Thursday)~~ 26th March 2023 (Sunday) 11.59pm (midnight).

## Learning from senior

You are advised to review these sample submissions prepared by your seniors.

-   [Take-Home Exercise 3: Hedonic Pricing Models for Resale Prices of Public Housing in Singapore](https://is415-msty.netlify.app/posts/2021-10-25-take-home-exercise-3/) by MEGAN SIM TZE YEN.

-   [Take-home Exercise 3](https://aisyahajit2018-is415.netlify.app/posts/2021-11-07-take-home-exercise-3/) by NOR AISYAH BINTE AJIT.

## Q & A

Please submit your questions or queries related to this take-home exercise on Piazza.

## Peer Learning

-   [AILYS TEE XYNYN](https://is415-ailystee.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [ALANIS ZOE CHIA HUI LIN](https://is415-zoechia.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [ANNA TSENG RUI-WEN](https://annatrw-is415.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [CELINE NG SI LIN](https://is415-gaa.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)

-   [CHEN HAO XIAN](https://master--is415-gaa-hxchen.netlify.app/lessons/take-home/take-home_ex3/take-home_ex3)

-   [DANIEL CHNG CHONG YEE](https://celebrated-truffle-4b528c.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [DEREK POH YONG JIE](https://derekpoh-is415.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [ESWARA LAKSHMANAN ABISHEK](https://is415-elabishek.netlify.app/takehome_exercise/takehome3/takehome3)

-   [HARITH OH YEE CHOON](https://is415-harith.netlify.app/take-home_ex3/take_home_ex3)

-   [HO YONG QUAN](https://is415-gaa-yongquan.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [HOW XIN YEE](https://is415-xinyeehow.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [JENNIFER POERNOMO](https://jenpoer-is415-gaa-exercises.netlify.app/take-home-exercises/exe-03/the3)

-   [KUMARAPANDIAN YASHICARAMYA](https://is415-gaa-xtc0.netlify.app/take-home_ex/take_home_ex03/take-home_ex03)

-   [KWANG KAI XUAN BELLE](https://melodious-kelpie-bd4c0d.netlify.app/take_home_ex/the3/the3)

-   [KWEK MING RONG](https://is415-gaa-kwekmingrong.netlify.app/take_home_ex/take_home_ex3)

-   [LEE CHIA MIN MICHELLE FAITH](https://is415-gaa-michellefaith.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [LEON TAN LI YANG](https://capable-arithmetic-46d74a.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [LU QUANFANG](https://is415quanfang.netlify.app/takehome_exercise/takehome_exercise3/takehome_ex03)

-   [MICHELLE LEONG HWEE-LING](https://is415-shelle-mim.netlify.app/take-home_exercise/th3/th_ex3)

-   [NGUYEN MAI PHUONG](https://is415-gaa-tiffanik.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [PENG YOU YUN](https://youyunpeng-is415.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [PIERRE JEAN MICHEL HAAS](https://is415-pierrehaas.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [RHONDA HO KAH YEE](https://rhondaho-is415.netlify.app/take-home_assgn/take-home_assgn3/take-home_assgn3)

-   [S GUGANESH](https://is415-gaa-guganesh.netlify.app/take-home_ex/take-home_ex03/take-home_ex03.html)

-   [SALUNKE MAYURI MILIND](https://is415-mayurims.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [SHAMBHAVI GOENKA](https://shambhavig.netlify.app/take_home_ex/take_home_ex03/take_home_ex03.html)

-   [SHAYTHURAM SO ELANGKOVAN]()

-   [SHERRY NG SHEA LI](https://cosmic-muffin-95669c.netlify.app/take-home_ex/take-home_ex03/takehome_ex03)

-   [TAN WEI SHING]()

-   [TAN WEN YANG](https://is415-gaa-wy.netlify.app/take-home-ex/take-home-ex03/take-home-ex03.html)

-   [TAN YAN LIN VALENCIA](https://is415-gaa-valtyl.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [TEH JIA HUI GAIL](https://is415-gaa-gailteh.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [TEO JUN HAO](https://is415-gaa-junhao.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [TEO REN JIE](https://renjieteo-is415.netlify.app/exercises/thex03.html)

-   [TONG XUE YU KATHY](https://is415-gaa-kathy.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

-   [WONG KELLY](https://is415kellysite.netlify.app/take_home_ex/take_home_ex03/take_home_ex03_updated)
