---
title: "Lesson 9: Geograpgically Weighted Regression"
description: |
  In this lesson, you will learn the basic concepts and methods of geographically weighted regression.
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Content
- Basic concepts and principles of linear regression
    - Simple linear regression
    - Multiple linear regression
- The spatial stationarity assumption of multiple linear regression.
- Introducing Geographically Weighted Regression
    - Weighting functions (kernel)
    - Weighting schemes
    - Bandwidth
    - Interpreting and Visualising 

## Lesson Slides and Hands-on Notes 

- Lesson slides in [html](../lesson/lesson09/lesson09-gwr.html) and [pdf](../lesson/lesson09/lesson09-gwr.pdf) formats

- Handout of Hands-on Exercise 9 in [html](../Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09-gwr.html) and [pdf](../Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09-gwr.pdf) formats.


## Self-reading Before Meet-up

To read before class:

- Brunsdon, C., Fotheringham, A.S., and Charlton, M. (2002) “Geographically weighted regression: A method for exploring spatial nonstationarity”. Geographical Analysis, 28: 281-289.
- Brunsdon, C., Fotheringham, A.S. and  Charlton, M., (1999) “Some Notes on Parametric Significance Tests for Geographically Weighted Regression”. Journal of Regional Science, 39(3), 497-524.

## References
- Mennis, Jeremy (2006) "Mapping the Results of Geographically Weighted Regression", The Cartographic Journal, Vol.43 (2), p.171-179.
- Stephen A. Matthews ; Tse-Chuan Yang (2012) "Mapping the results of local statistics: Using geographically weighted regression", Demographic Research, Vol.26, p.151-166.

## All About R
- [**GWmodel**](https://cran.r-project.org/web/packages/GWmodel/) package, especially 
    - Gollini, I et. al. (2015) [“GWmodel: An R Package for Exploring Spatial Heterogeneity Using Geographically Weighted Models”](https://www.jstatsoft.org/article/view/v063i17), *Journal of Statistical Software*, Volume 63, Issue 17 and 
    - Binbin Lu, Paul Harris, Martin Charlton & Chris Brunsdon (2014) [“The GWmodel R package: further topics for exploring spatial heterogeneity using geographically weighted models”](https://www.tandfonline.com/doi/full/10.1080/10095020.2014.917453), *Geo-spatial Information Science*, 17:2, 85-101, DOI: 10.1080/10095020.2014.917453.
- [**lctools**](https://cran.r-project.org/web/packages/lctools/index.html) package especially *gw()* and *gwr()* related functions.
- [**spgwr**](https://cran.r-project.org/web/packages/spgwr/index.html) implements of geographically weighted regression methods for exploring possible non-stationarity.
- [**gwrr**](https://cran.r-project.org/web/packages/gwrr/index.html): its geographically weighted regression (GWR) models and has tools to diagnose and remediate collinearity in the GWR models. Also fits geographically weighted ridge regression (GWRR) and geographically weighted lasso (GWL) models.  





